wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.12
    is_jupyter_run: false
    magic:
      enable: true
      epochs:
        desc: Number of epochs to train over
        value: 3
      tokenizer_class:
        desc: Class to be used on tokenizer
    python_version: 3.7.3
seed:
  desc: null
  value: 42
